# 使用官方的 Node.js 镜像作为基础镜像
FROM node:18

# 创建并设置工作目录
WORKDIR /usr/src/app

# 复制 package.json 和 package-lock.json 文件到工作目录
COPY package*.json ./

# 安装项目依赖
RUN npm install

# 复制项目文件到工作目录
COPY . .

# 暴露应用端口
EXPOSE 5000
    
# 启动应用
CMD ["node", "server.js"]
